### ISSUE TITLE
Reading Processed Historical Data through ReadProcessedDetails Class through freeOPCUA

### ISSUE THREAD

**Issue by rajnishnationfirst** [FreeOpcUa/python-opcua#1104]
Hi Colleagues,

I am trying to Processed  Historical Data using ReadProcessedDetails Object passed as param in history_read(params) function of OPCUA Python.

I am getting errors when i am configuring the objects using ReadProcessDetails and throwing some errors on Object Mismatch when ReadProcessedDetails Object configured and passed to history_read(params).

My Code : 
```

def do_transaction_history(client, nodes, start, end,processinterval,type, contes=None):
    client.connect()
    if contes is None:
        contes = [b''] * len(nodes)

    **#Configuring ReadProcessedDetails Object**
    details2 = ua.ReadProcessedDetails()
    details2.StartTime=start
    details2.EndTime = end
    details2.ProcessingInterval= processinterval
    details2.AggregateType =[]
    details2.AggregateConfiguration = nodes

 
    **#Configuring HistoryReadParameters Object**
    params = ua.HistoryReadParameters()
    params.HistoryReadDetails = details2
    params.TimestampsToReturn = ua.TimestampsToReturn.Source
    params.ReleaseContinuationPoints = False

    **#passing the readprocesseddetails to history_read Object**
    for n in nodes:
        valueid = ua.HistoryReadValueId()
        valueid.NodeId = n.nodeid
        valueid.IndexRange = ''
        valueid.ContinuationPoint = c
        params.NodesToRead.append(valueid)
        result = client.uaclient.history_read(params)
    
    return result
```

But i am getting errors at  **client.uaclient.history_read(params)**   with the follwing errors thrown.

<img width="960" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/64892368/87538237-8886b380-c6b9-11ea-9f11-98c121112e08.png">

Cosole Errors Raised Detailed:

[4:27 PM] Surangalikar, Prachi (RC-IN DI CS SD OS&SO PD)
    C:\Users\WinCC\untitled\Scripts\python.exe C:/Users/WinCC/PycharmProjects/untitled/read_aggregated_data.py
Constructor Called
Data
500
opc.tcp://EC2AMAZ-VJQV23P:4862 opc.tcp
MessageSecurityMode.None_ MessageSecurityMode.None_
http://opcfoundation.org/UA/SecurityPolicy#None http://opcfoundation.org/UA/SecurityPolicy#None
Traceback (most recent call last):
  File "C:/Users/WinCC/PycharmProjects/untitled/read_aggregated_data.py", line 89, in <module>
    test_procdata_history(p1.get_WinCC_Siemens_HDA_Client_Connection())
  File "C:/Users/WinCC/PycharmProjects/untitled/read_aggregated_data.py", line 71, in test_procdata_history
    result = do_transaction_history(client, nodes, start, end, processinterval,type,contes)
  File "C:/Users/WinCC/PycharmProjects/untitled/read_aggregated_data.py", line 42, in do_transaction_history
    result = client.uaclient.history_read(params)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\client\ua_client.py", line 602, in history_read
    data = self._uasocket.send_request(request)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\client\ua_client.py", line 81, in send_request
    future = self._send_request(request, callback, timeout, message_type)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\client\ua_client.py", line 55, in _send_request
    binreq = struct_to_binary(request)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 258, in struct_to_binary
    packet.append(to_binary(uatype, val))
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 281, in to_binary
    return struct_to_binary(val)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 258, in struct_to_binary
    packet.append(to_binary(uatype, val))
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 271, in to_binary
    return pack_uatype(vtype, val)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 185, in pack_uatype
    return extensionobject_to_binary(value)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 457, in extensionobject_to_binary
    Body = struct_to_binary(obj)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 253, in struct_to_binary
    packet.append(list_to_binary(uatype[6:], val))
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 293, in list_to_binary
    pack = [to_binary(uatype, el) for el in val]
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 293, in <listcomp>
    pack = [to_binary(uatype, el) for el in val]
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 271, in to_binary
    return pack_uatype(vtype, val)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 187, in pack_uatype
    return nodeid_to_binary(value)
  File "C:\Users\WinCC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\opcua\ua\ua_binary.py", line 300, in nodeid_to_binary
    if nodeid.NodeIdType == ua.NodeIdType.TwoByte:
AttributeError: 'str' object has no attribute 'NodeIdType'
 

It will be great if anyone can help me with the above errors and assisting me on configuring ReadProcessedDetails with history_read parameters.

Thanks & Regards'
Rajnish Vishwakarma

**Comment by AndreasHeine** [comment]
i would guess this is not correct:
**details2.AggregateType =['Min','Max','Avg']**

> 'str' object has no attribute 'NodeIdType'

    ua_types = [
        ('StartTime', 'DateTime'),
        ('EndTime', 'DateTime'),
        ('ProcessingInterval', 'Double'),
        ('AggregateType', 'ListOfNodeId'), <--------------------------------------------------!!!!!!!
        ('AggregateConfiguration', 'AggregateConfiguration'),
               ]

```python
class ReadProcessedDetails(FrozenClass):
    """
    :ivar StartTime:
    :vartype StartTime: DateTime
    :ivar EndTime:
    :vartype EndTime: DateTime
    :ivar ProcessingInterval:
    :vartype ProcessingInterval: Double
    :ivar AggregateType:
    :vartype AggregateType: NodeId
    :ivar AggregateConfiguration:
    :vartype AggregateConfiguration: AggregateConfiguration
    """

    ua_types = [
        ('StartTime', 'DateTime'),
        ('EndTime', 'DateTime'),
        ('ProcessingInterval', 'Double'),
        ('AggregateType', 'ListOfNodeId'),
        ('AggregateConfiguration', 'AggregateConfiguration'),
               ]

    def __init__(self):
        self.StartTime = datetime.utcnow()
        self.EndTime = datetime.utcnow()
        self.ProcessingInterval = 0
        self.AggregateType = []
        self.AggregateConfiguration = AggregateConfiguration()
        self._freeze = True

    def __str__(self):
        return 'ReadProcessedDetails(StartTime:{self.StartTime}, EndTime:{self.EndTime}, ProcessingInterval:{self.ProcessingInterval}, AggregateType:{self.AggregateType}, AggregateConfiguration:{self.AggregateConfiguration})'

    __repr__ = __str__
```
