### ISSUE TITLE
OPC DA to OPC UA wrapper for Schneider-Aut.OFS.2

### ISSUE THREAD

**Issue by AliRaza0304444** [FreeOpcUa/python-opcua#1310]
I have implemented the following code from the following link
https://github.com/FreeOpcUa/python-opcua/issues/489
The code is working fine for OPC Makrikon but I cannot connect with Schneider.

I have also tried adding Schneider-Aut.OFS in OpenOPC.py file but no success. 

following error appears 
Traceback (most recent call last):
  File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenOPC.py", line 223, in connect
    self._opc.Connect(s, opc_host)
  File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\site-packages\win32com\gen_py\F8582D24-88FB-11D0-B850-00C0F0104305x0x1x0.py", line 207, in Connect
    return self._oleobj_.InvokeTypes(1610743826, LCID, 1, (24, 0), ((8, 1), (12, 17)),ProgID
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, 'The endpoint is a duplicate.\r\n', None, 0, -2147467259), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alraza\RemoteOPC.py", line 51, in <module>
    c.connect(OPC_DA_SERVER,'172.16.6.181')
  File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenOPC.py", line 227, in connect
    raise OPCError(error_msg)
OpenOPC.OPCError: Connect: -2147467259

**Comment by AndreasHeine** [comment]
wrong repo! 
**this error is not related to python-opcua**
