### ISSUE TITLE
error when reconnecting to server

### ISSUE THREAD

**Issue by iamthebull** [FreeOpcUa/python-opcua#1549]
I wrote a simple opcua client using `python-asyncua` and `PyQt6`.

After starting the program I click the connect button to connect to the server. Then click disconnect to disconnect. At this point everything is working fine. Then when I click connect to connect again I get an error.

My code:
```
import sys
from PyQt6.QtCore import Qt, pyqtSignal, pyqtSlot
from PyQt6.QtWidgets import (
							QApplication, QMainWindow, QWidget, QGridLayout, QHBoxLayout,
							QVBoxLayout, QLabel, QMessageBox, QLineEdit, QPushButton,
							QToolButton, QFileDialog, QSpacerItem, QSizePolicy)
from asyncua.sync import Client
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(msg)s')
logger = logging.getLogger(__file__)

class OPCTag():
	def __init__(self, name, nodeId, addNode) -> None:
		self.name = name
		self.nodeId = nodeId
		self.handle = self.addNode(addNode)
	
	def addNode(self, addNode):
		return addNode(self.nodeId)

	def remove(self, remNode):
		remNode(self.nodeId, self.handle)
		self.handle = None

class OPCTags():
	def __init__(self, addNode, remNode) -> None:
		self.tags = {}
		self.addNode = addNode
		self.remNode = remNode
	
	def addTag(self, name, nodeId):
		self.tags[name] = OPCTag(name, nodeId, self.addNode)
		logger.info(f'tags: [{name}] added')
	
	def getTag(self, name):
		return self.tags[name] if name in self.tags else None
	
	def remTag(self, name):
		if name in self.tags:
			self.getTag(name).remove(self.remNode)
			self.tags.pop(name)
			logger.info(f'tags: [{name}] removed')
	
	def remAllTags(self):
		for name in [name for name in self.tags]:
			self.remTag(name)
		logger.info('tags: removed all')
	
	def printAll(self):
		items = self.tags.items()
		logger.info(f'tags: total = {len(items)}')
		for name, tag in items:
			msg = f'tag: {name} - [ '
			for key, val in tag.__dict__.items():
				msg += f' {key} : {val} |'
			msg = msg[:-1] + ']'
			logger.info(msg)

class DataChangeHandler():
	def datachange_notification(self, node, val, data):
		logger.info('data change | node: {node} | value: {val}')

class MainWindow(QMainWindow):
	def __init__(self):
		super().__init__()
		self.setWindowTitle("OPC-UA Client")

		# opcua client
		self.url = 'opc.tcp://10.0.1.56:55105'
		self.client = Client(self.url)
		self.handler = DataChangeHandler()
		self.sub = None

		# tags
		self.tags = OPCTags(self.addNode, self.remNode)

		# gui widgets
		btnConnect = QPushButton('Connect')
		btnConnect.clicked.connect(self.connect)

		btnDisconnect = QPushButton('Disconnect')
		btnDisconnect.clicked.connect(self.disconnect)

		btnAddTag1 = QPushButton('Add Tag 1')
		btnAddTag1.clicked.connect(self.addTag1)
		
		btnRemTag1 = QPushButton('Rem Tag 1')
		btnRemTag1.clicked.connect(self.remTag1)

		btnAddTag2 = QPushButton('Add Tag 2')
		btnAddTag2.clicked.connect(self.addTag2)
		
		btnRemTag2 = QPushButton('Rem Tag 2')
		btnRemTag2.clicked.connect(self.remTag2)

		btnRemAllTags = QPushButton('Rem All Tags')
		btnRemAllTags.clicked.connect(self.remAllTags)

		btnPrintTags = QPushButton('Print All Tags')
		btnPrintTags.clicked.connect(self.printAll)

		btnPrintMonitoredItems = QPushButton('Print Monitored Items')
		btnPrintMonitoredItems.clicked.connect(self.printMonitoredItems)

		self.appLayout = QVBoxLayout()
		spacerParams = 0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding
		self.appLayout.addWidget(btnConnect)
		self.appLayout.addWidget(btnDisconnect)
		self.appLayout.addSpacerItem(QSpacerItem(*spacerParams))
		self.appLayout.addWidget(btnAddTag1)
		self.appLayout.addWidget(btnRemTag1)
		self.appLayout.addSpacerItem(QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding))
		self.appLayout.addWidget(btnAddTag2)
		self.appLayout.addWidget(btnRemTag2)
		self.appLayout.addSpacerItem(QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding))
		self.appLayout.addWidget(btnRemAllTags)
		self.appLayout.addSpacerItem(QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding))
		self.appLayout.addWidget(btnPrintTags)
		self.appLayout.addWidget(btnPrintMonitoredItems)

		self.container = QWidget()
		self.container.setLayout(self.appLayout)

		self.setCentralWidget(self.container)

	@pyqtSlot()
	def connect(self):
		try:
			self.client.connect()
			logger.info('client connected')
		except Exception as err:
			logger.exception('error connecting server')

	@pyqtSlot()
	def disconnect(self):
		try:
			self.client.disconnect()
			logger.info('client disconnected')
		except Exception as err:
			logger.exception('error disconnecting server')
	
	def addNode(self, nodeId):
		rootNodeId = 'ns=6;s=S71500ET200MP station_1.PLC_1.Data_block_1.'
		handle = None
		try:
			if not self.sub:
				self.sub = self.client.create_subscription(500, self.handler)
			node = self.client.get_node(rootNodeId + nodeId)
			handle = self.sub.subscribe_data_change(node)
		except Exception as err:
			logger.exception('error adding node')
		return handle

	def remNode(self, nodeId, handle):
		try:
			self.sub.unsubscribe(handle)
		except Exception as err:
			logger.exception('error removing node')

	@pyqtSlot()
	def printMonitoredItems(self):
		for key, obj in self.sub._monitoreditems_map.items():
			print(key)
			for key, val in obj.__dict__.items():
				print(f'  {key} : {val}')

	@pyqtSlot()
	def addTag1(self):
		self.tags.addTag('Tag 1', 'int1')

	@pyqtSlot()
	def remTag1(self):
		self.tags.remTag('Tag 1')
	
	@pyqtSlot()
	def addTag2(self):
		self.tags.addTag('Tag 2', 'int2')

	@pyqtSlot()
	def remTag2(self):
		self.tags.remTag('Tag 2')
	
	@pyqtSlot()
	def remAllTags(self):
		self.tags.remAllTags()

	@pyqtSlot()
	def printAll(self):
		self.tags.printAll()
		
def main():
	logger.info('starting app')
	app = QApplication(sys.argv)
	main = MainWindow()
	main.show()
	sys.exit(app.exec())

if __name__ == '__main__':
	main()
```

Here is the output to the console:
```
$  cd /home/david/python/opcua ; /usr/bin/env /home/david/python/opcua/.venv/bin/python3 /home/david/.vscode/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 43871 -- /home/david/python/opcua/qt.py 
2024-09-24 20:49:55,723 - INFO - starting app
2024-09-24 20:49:57,790 - INFO - connect
2024-09-24 20:49:57,790 - INFO - opening connection
2024-09-24 20:49:57,793 - INFO - updating client limits to: %s
2024-09-24 20:49:57,793 - INFO - open_secure_channel
2024-09-24 20:49:57,796 - INFO - create_session
2024-09-24 20:49:57,800 - INFO - find_endpoint %r %r %r
2024-09-24 20:49:57,801 - INFO - activate_session
2024-09-24 20:49:57,806 - INFO - client connected
2024-09-24 20:49:59,727 - INFO - disconnect
2024-09-24 20:49:59,727 - INFO - close_session
2024-09-24 20:49:59,730 - INFO - close_secure_channel
2024-09-24 20:49:59,730 - INFO - Request to close socket received
2024-09-24 20:49:59,731 - INFO - Socket has closed connection
2024-09-24 20:49:59,732 - INFO - client disconnected
2024-09-24 20:50:02,022 - ERROR - error connecting server
Traceback (most recent call last):
  File "/home/david/python/opcua/qt.py", line 130, in connect
    self.client.connect()
  File "/home/david/python/opcua/.venv/lib/python3.12/site-packages/asyncua/sync.py", line 110, in wrapper
    result = self.tloop.post(aio_func(*args, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/python/opcua/.venv/lib/python3.12/site-packages/asyncua/sync.py", line 64, in post
    raise ThreadLoopNotRunning(f"could not post {coro} since asyncio loop in thread has not been started or has been stopped")
asyncua.sync.ThreadLoopNotRunning: could not post <coroutine object Client.connect at 0x70a25c1a4450> since asyncio loop in thread has not been started or has been stopped
/home/david/python/opcua/qt.py:133: RuntimeWarning: coroutine 'Client.connect' was never awaited
  logger.exception('error connecting server')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

```
$ pip show asyncua
Name: asyncua
Version: 1.1.5
Summary: Pure Python OPC-UA client and server library
Home-page: http://freeopcua.github.io/
Author: Olivier Roulet-Dubonnet
Author-email: olivier.roulet@gmail.com
License: GNU Lesser General Public License v3 or later
Location: /home/david/python/opcua/.venv/lib/python3.12/site-packages
Requires: aiofiles, aiosqlite, cryptography, pyOpenSSL, python-dateutil, pytz, sortedcontainers, typing-extensions
Required-by:
```

```
$ uname -a
Linux DevLaptop 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by iamthebull** [comment]
Oops wrong repo. Closing and re-posting in asyncua
