### ISSUE TITLE
Matrikon UA Wrapper responds with BadInvalidTimestamp

### ISSUE THREAD

**Issue by burk3** [FreeOpcUa/python-opcua#251]
In my client code, and when using `uals` against a Matrikon UA Wrapper server, I'm greeted with a `BadInvalidTimestamp`, which seems to indicate that the timestamp on some request the client library is sending is somehow "bad". Cursory googling had me make the timestamps try and match by aligning the server timezone to the client timezone, but this did not work.

```
uals -u opc.tcp://example.com:21381/MatrikonOpcUaWrapper
Browsing node Node(NumericNodeId(i=84)) at opc.tcp://example.com:21381/MatrikonOpcUaWrapper

DisplayName                    NodeId                    BrowseName                Value                    

WARNING: ServiceFault from server received  in response to BrowseRequest
WARNING: ServiceFault from server received  in response to CloseSessionRequest
Traceback (most recent call last):
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/tools.py", line 283, in uals
    _lsprint_1(node, args.depth - 1)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/tools.py", line 307, in _lsprint_1
    for desc in node.get_children_descriptions():
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/common/node.py", line 259, in get_children_descriptions
    results = self.server.browse(params)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 261, in browse
    data = self._uasocket.send_request(request)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 76, in send_request
    self.check_answer(data, " in response to " + request.__class__.__name__)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 85, in check_answer
    hdr.ServiceResult.check()
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/ua/uatypes.py", line 325, in check
    raise UaStatusCodeError("{}({})".format(self.doc, self.name))
opcua.common.uaerrors.UaStatusCodeError: The timestamp is outside the range allowed by the server.(BadInvalidTimestamp)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bcates/.virtualenvs/opc3/bin/uals", line 11, in <module>
    sys.exit(uals())
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/tools.py", line 287, in uals
    client.disconnect()
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/client.py", line 217, in disconnect
    self.close_session()
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/client.py", line 412, in close_session
    return self.uaclient.close_session(True)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 253, in close_session
    data = self._uasocket.send_request(request)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 76, in send_request
    self.check_answer(data, " in response to " + request.__class__.__name__)
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/client/ua_client.py", line 85, in check_answer
    hdr.ServiceResult.check()
  File "/Users/bcates/.virtualenvs/opc3/lib/python3.5/site-packages/opcua/ua/uatypes.py", line 325, in check
    raise UaStatusCodeError("{}({})".format(self.doc, self.name))
opcua.common.uaerrors.UaStatusCodeError: The timestamp is outside the range allowed by the server.(BadInvalidTimestamp)
```

Any more debug info I can provide?

**Comment by oroulet** [comment]
record a session with wireshark when the fails happen and another one when reading with uaexpert. We will then be able to spot difference. I cannot see where there is a timestamp in a read operation.....

**Comment by thephez** [comment]
I've just encountered this `BadInvalidTimestamp` error while attempting to connect to an OPCFoundation .NET Core based server.  The bad timestamp is coming from the BrowseRequest being sent from the client and (as reported by Wireshark) is off by 5 hours.  This happens to be my offset from UTC.

I did some digging and found that I could get it to work by changing the `datetime.now()` reference on
[line 1271 of uaprotocol_auto.py](https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/ua/uaprotocol_auto.py#L1271) to `datetime.utcnow()`.  

My understanding is that OPC timestamps are supposed to be in UTC.  I don't know if the conversion is supposed to be happening some other way, but wanted to report what I found.

**Comment by oroulet** [comment]
thanks @thephez ! fix commited https://github.com/FreeOpcUa/python-opcua/commit/ddd4278ba506cf5c65e89b653b2205a594f5dbcc
