### ISSUE TITLE
opc ua client in raspberrypi

### ISSUE THREAD

**Issue by ghost** [FreeOpcUa/python-opcua#458]
Hello, All.

I am building an OPC UA Server and Client with two RaspberryPi2 Model B, respectively.

The problem occurs on the client as follows: What is the problem?
(Note that the client works fine in Ubuntu on the desktop.)

```
Traceback (most recent call last):
  File "test_opcua_client.py", line 27, in <module>
    client.disconnect()
  File "../opcua/client/client.py", line 258, in disconnect
    self.disconnect_socket()
  File "../opcua/client/client.py", line 267, in disconnect_socket
    self.uaclient.disconnect_socket()
  File "../opcua/client/ua_client.py", line 218, in disconnect_socket
    return self._uasocket.disconnect_socket()
  File "../opcua/client/ua_client.py", line 143, in disconnect_socket
    self._socket.socket.shutdown(socket.SHUT_RDWR)
AttributeError: 'NoneType' object has no attribute 'socket'
```

**Comment by zerox1212** [comment]
Are you using Python 2 or 3?

**Comment by aquari89** [comment]
python2.

2017. 6. 15. 오전 2:52에 "Andrew" <notifications@github.com>님이 작성:

**Comment by aquari89** [comment]
It works fine with python3.

I do not know why the above case occurs for some reason.
Could you tell me if you know?

**Comment by zerox1212** [comment]
At the moment I do not know, but some async libraries are no longer in development which makes Python 2 work, so you should try to use Python. Going forward python opcua might drop support for Python 2 because it's becoming difficult to support.
