### ISSUE TITLE
EnumBadKeyError: Enumeration keys must be strings: 6

### ISSUE THREAD

**Issue by mustafacamurli** [FreeOpcUa/python-opcua#50]
Hi,

I'm using this "http://open62541.org/" opcua server running on my pc.

Right after i connect to the server, i'm getting this exception:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/opcua/client.py", line 41, in run
    val = server_state.get_value()
  File "/usr/lib/python2.7/site-packages/opcua/node.py", line 168, in get_value
    result = self.get_data_value()
  File "/usr/lib/python2.7/site-packages/opcua/node.py", line 177, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
  File "/usr/lib/python2.7/site-packages/opcua/node.py", line 234, in get_attribute
    result = self.server.read(params)
  File "/usr/lib/python2.7/site-packages/opcua/binary_client.py", line 317, in read
    response = ua.ReadResponse.from_binary(data)
  File "/usr/lib/python2.7/site-packages/opcua/uaprotocol_auto.py", line 6689, in from_binary
    obj.Results.append(DataValue.from_binary(data))
  File "/usr/lib/python2.7/site-packages/opcua/uatypes.py", line 858, in from_binary
    obj.Value = Variant.from_binary(data)
  File "/usr/lib/python2.7/site-packages/opcua/uatypes.py", line 782, in from_binary
    obj.VariantType = VariantType(val)
  File "/usr/lib/python2.7/site-packages/enum-0.4.4-py2.7.egg/enum.py", line 197, in __init__
    raise EnumBadKeyError(key)
EnumBadKeyError: Enumeration keys must be strings: 6

**Comment by oroulet** [comment]
You installed wrong enum package. Enum34 is the one
