### ISSUE TITLE
calling client.disconnect creates exception when client is not connected to server

### ISSUE THREAD

**Issue by daniel-brosche** [FreeOpcUa/python-opcua#522]
The following exception occurs:

```python
Traceback (most recent call last):
  File "lenze_ua_server_test.py", line 32, in test_connect__simple__shouldsuccess
    client.disconnect()
  File "./python_opcua/opcua/client/client.py", line 261, in disconnect
    self.disconnect_socket()
  File "./python_opcua/opcua/client/client.py", line 270, in disconnect_socket
    self.uaclient.disconnect_socket()
  File "./python_opcua/opcua/client/ua_client.py", line 221, in disconnect_socket
    return self._uasocket.disconnect_socket()
  File "./python_opcua/opcua/client/ua_client.py", line 144, in disconnect_socket
    self._socket.socket.shutdown(socket.SHUT_RDWR)
AttributeError: 'NoneType' object has no attribute 'socket'
```

In my opinion an exception like this is not helpful to understand and `client.disconnect` should just do nothing when a client is not connected.

**Comment by oroulet** [comment]
yes you could send a PR checking if socket or any other object is created
