### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by tompropst** [FreeOpcUa/python-opcua#543]
Hello,
Attempting to connect to a public OPC server from Mac OS X fails.
I am testing `opc.tcp://uademo.prosysopc.com:53530/OPCUA/SimulationServer` using the example code. The relevant output is:

```
INFO:opcua.client.ua_client.Socket:opening connection
INFO:opcua.client.ua_client:close_session
DEBUG:opcua.client.ua_client.Socket:Sending: CloseSessionRequest(TypeId:FourByte
NodeId(i=473), RequestHeader:RequestHeader(AuthenticationToken:TwoByteNodeId(i=0
), Timestamp:2018-01-10 17:21:17.319511, RequestHandle:1, ReturnDiagnostics:0, A
uditEntryId:None, TimeoutHint:1000, AdditionalHeader:None), DeleteSubscriptions:
True)
INFO:opcua.client.ua_client.Socket:stop request
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    client.connect()
  File "/Users/trp/repos/python-opcua/venv/lib/python3.6/site-packages/opcua/cli
ent/client.py", line 243, in connect
    self.connect_socket()
  File "/Users/trp/repos/python-opcua/venv/lib/python3.6/site-packages/opcua/cli
ent/client.py", line 264, in connect_socket
    self.uaclient.connect_socket(self.server_url.hostname, self.server_url.port)
  File "/Users/trp/repos/python-opcua/venv/lib/python3.6/site-packages/opcua/cli
ent/ua_client.py", line 215, in connect_socket
    return self._uasocket.connect_socket(host, port)
  File "/Users/trp/repos/python-opcua/venv/lib/python3.6/site-packages/opcua/client/ua_client.py", line 135, in connect_socket
    sock = socket.create_connection((host, port))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by tompropst** [comment]
I am sorry. I put this aside shortly after submitting this issue. I just went back and tested it and see a successful connection. I can't say for sure if I made a change before putting this aside or not. Regardless, it doesn't seem to be an issue now.
