### ISSUE TITLE
Help Needed: How to get all variable values from server

### ISSUE THREAD

**Issue by siddharth-lakhara** [FreeOpcUa/python-opcua#587]
I'm new to OPC, hence clueless about the issue faced

My server code

`import signal
import sys
from opcua import ua, Server

server = Server()
server.set_endpoint("opc.tcp://siddharth:9999/data")
uri = "http://siddharth:9999/data"
idx = server.register_namespace(uri)

objects = server.get_objects_node()
myobj = objects.add_object(idx, "status")
pressure = myobj.add_variable(idx, "pressure", 0)
sensor = myobj.add_variable(idx, "sensor", "working OK")
temperature = myobj.add_variable(idx, "temperature", 22)
pressure.set_writable()
sensor.set_writable()
temperature.set_writable()

server.start()
print "Server Started"`

I want to get the variable values from python client. I went through client-minimal example. Tried similar stuff, but no luck

My implementation of Client is as follows:
`import opcua

client = opcua.Client("opc.tcp://siddharth:9999/data")
try:
    client.connect()      
    root = client.get_root_node()
    child_root = root.get_children()
    child = child_root[0].get_children()
    print child[1] # got node value from this
    node = client.get_node("ns=2;i=1")
    print node.get_value()
finally:
    client.disconnect()
`

get_value function gives me the following error:
`Traceback (most recent call last):
  File "uaClient.py", line 11, in <module>
    print node.get_value()
  File "C:\Python27\lib\site-packages\opcua\common\node.py", line 146, in get_value
    result = self.get_data_value()
  File "C:\Python27\lib\site-packages\opcua\common\node.py", line 155, in get_data_value
    return self.get_attribute(ua.AttributeIds.Value)
  File "C:\Python27\lib\site-packages\opcua\common\node.py", line 262, in get_attribute
    result[0].StatusCode.check()
  File "C:\Python27\lib\site-packages\opcua\ua\uatypes.py", line 235, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadAttributeIdInvalid: The attribute is not supported for the specified Node.(BadAttributeIdInvalid)
`

**Comment by zerox1212** [comment]
Download UA Expert as a test client. Browse your server with UA Expert and then you will have a better idea what commands to use in your client to get the node and value you want.
