### ISSUE TITLE
B&R OPCUA Connection Error

### ISSUE THREAD

**Issue by aurangzaib** [FreeOpcUa/python-opcua#728]
I am trying to connect to B&R OPC-UA server.
The device is: B&R X20BC008U.
The connection is without authentication.

I am able to connect to the server using uaExpert.
But opcua-client gives the following error:
"Received an error: MessageAbort(error:StatusCode(Good), reason:)')"

### Error Dump:
`uaclient.uaclient - INFO - Connecting to opc.tcp://192.168.1.1:4840 with parameters None, None, None, None')
opcua.uaprotocol - WARNING - Received an error: MessageAbort(erro	r:StatusCode(Good), reason:)')
opcua.client.ua_client.Socket - WARNING - Received an error: MessageAbort(error:StatusCode(Good), reason:)')
uaclient.mainwindow - WARNING - showing error: %s')
uawidgets.utils - ERROR - ')
Traceback (most recent call last):
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\uawidgets\utils.py", line 21, in wrapper
    result = func(self, *args)
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\uaclient\mainwindow.py", line 338, in connect
    self.uaclient.connect(uri)
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\uaclient\uaclient.py", line 94, in connect
    self.client.connect()
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\opcua\client\client.py", line 260, in connect
    self.create_session()
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\opcua\client\client.py", line 378, in create_session
    response = self.uaclient.create_session(params)
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\opcua\client\ua_client.py", line 248, in create_session
    data = self._uasocket.send_request(request)
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\site-packages\opcua\client\ua_client.py", line 77, in send_request
    data = future.result(self.timeout)
  File "c:\users\k0927899\miniconda3\envs\pet_bottles\lib\concurrent\futures\_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
uaclient.mainwindow - WARNING - showing error: %s')`

--------------------------------------------------------------------------------------------------------

I do not understand what is causing this error. Any help from fellow colleagues would be much appreciated. Thanks.

**Comment by urianchang** [comment]
Do you see an error message shown in the log messages (for [reference](https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/client/ua_client.py#L112-L113))?
