### ISSUE TITLE
Discovery clients should be outside of server.py code.

### ISSUE THREAD

**Issue by brubbel** [FreeOpcUa/python-opcua#733]
It seems to me that registration to OPC-UA discovery servers may be handled outside of the Server class, as a separate entity. Looking at the call graph, it would make the server.py code cleaner.
Will do a PR, then feel free to resist.

**Comment by brubbel** [comment]
https://github.com/FreeOpcUa/python-opcua/blob/fa52b1d863e1007cd4420c86f54485671329b00e/tests/tests_server.py#L54-L56
Setting an app_uri for register_to_discovery is useless since the registration basically doesn't involve the OPC-UA server that one wants to register. It just sets up a new client to announce the url of said server to the discovery server. So:

OPC-UA server with endpoint x (the one we want to announce)
    \_ associated discovery client -> [endpoint x announcement] -> OPC-UA discovery server.

**Comment by brubbel** [comment]
Confusing member names:
https://github.com/FreeOpcUa/python-opcua/blob/fa52b1d863e1007cd4420c86f54485671329b00e/opcua/server/server.py#L91-L92

discovery_clients should be called registration_clients. They take care of announcing/registering the server with an LDS server. discovery clients, on the other hand, connect to the LDS to find out the available server end points.

**Comment by brubbel** [comment]
Race condition when periodic re-registrations to LDS (asyncio thread) and server is stopped from main thread.

```
ERROR:asyncio:Exception in callback Server._renew_registration()
handle: <TimerHandle when=52137.077456338004 Server._renew_registration()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "./opcua/server/server.py", line 204, in _renew_registration
    client.register_server(self)
  File "./opcua/client/client.py", line 337, in register_server
    return self.uaclient.register_server(serv)
  File "./opcua/client/ua_client.py", line 364, in register_server
    data = self._uasocket.send_request(request)
  File "./opcua/client/ua_client.py", line 75, in send_request
    future = self._send_request(request, callback, timeout, message_type)
  File "./opcua/client/ua_client.py", line 66, in _send_request
    self._socket.write(msg)
  File "./opcua/common/utils.py", line 118, in write
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by brubbel** [comment]
There is a race condition where periodic registrations to LDS cause an error on the discovery server, due to a re-registration using a wrong ChannelId.
Cause: the registration client does not check if the SecureChannel received a close ('CLO') command and is in the closed state.
Clients should not register to a previously closed connection.
```
ERROR:opcua.server.binary_server_asyncio:Exception raised while parsing message from client, closing
Traceback (most recent call last):
  File "./opcua/server/binary_server_asyncio.py", line 75, in _process_data
    ret = self.processor.process(hdr, buf)
  File "./opcua/server/uaprocessor.py", line 80, in process
    msg = self._connection.receive_from_header_and_body(header, body)
  File "./opcua/common/connection.py", line 291, in receive_from_header_and_body
    return self._receive(chunk)
  File "./opcua/common/connection.py", line 322, in _receive
    self._check_incoming_chunk(msg)
  File "./opcua/common/connection.py", line 239, in _check_incoming_chunk
    self.channel.SecurityToken.ChannelId))
opcua.ua.uaerrors._base.UaError: Wrong channel id 0, expected 9
```
