### ISSUE TITLE
Possible race condition in ua_client.py

### ISSUE THREAD

**Issue by brubbel** [FreeOpcUa/python-opcua#735]
Not sure yet what triggers this. Just testing under heavy load.
```
ERROR:opcua.client.ua_client.Socket:Protocol Error
Traceback (most recent call last):
  File "./opcua/client/ua_client.py", line 95, in _run
    self._receive()
  File "./opcua/client/ua_client.py", line 108, in _receive
    self._call_callback(msg.request_id(), msg.body())
  File "./opcua/client/ua_client.py", line 122, in _call_callback
    .format(request_id, self._callbackmap.keys())
opcua.ua.uaerrors._base.UaError: No future object found for request: 123, callbacks in list are dict_keys([])
```

**Comment by brubbel** [comment]
It is caused by close_secure_channel invalidating the callbacks, self._callbackmap.clear():
https://github.com/FreeOpcUa/python-opcua/blob/fa52b1d863e1007cd4420c86f54485671329b00e/opcua/client/ua_client.py#L181-L193
This happens while the receiving thread is still alive. When a message is then received, it causes the above uaerror:
https://github.com/FreeOpcUa/python-opcua/blob/fa52b1d863e1007cd4420c86f54485671329b00e/opcua/client/ua_client.py#L91-L101

Solution: invalidate the callbackmap when the socket is actually closed.
