### ISSUE TITLE
Connection loss by client

### ISSUE THREAD

**Issue by OPCle** [FreeOpcUa/python-opcua#823]
Hi all, I am trying to identify a problem, which only occurs when using the server of my customer. Unfortunately, I can not  reconstruct this issue, because I have no access to their network/server - which makes the troubleshooting difficult... When using my server, the below error message never occurs. Please notice that the error occurs after my client successfully connected and also read values. 

`WARNING:opcua.client.ua_client.Socket:ServiceFault from server received while waiting for publish response
ERROR:concurrent.futures:exception calling callback for <Future at 0x4470c18 state=finished returned Buffer>
Traceback (most recent call last):
  File "C:\python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\python37\lib\site-packages\opcua\client\ua_client.py", line 463, in _call_publish_callback
    self._uasocket.check_answer(data, "while waiting for publish response")
  File "C:\python37\lib\site-packages\opcua\client\ua_client.py", line 88, in check_answer
    hdr.ServiceResult.check()
  File "C:\python37\lib\site-packages\opcua\ua\uatypes.py", line 233, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadSessionClosed: The session was closed by the client.(BadSessionClosed)
WARNING:opcua.client.ua_client.Socket:ServiceFault from server received while waiting for publish response
ERROR:concurrent.futures:exception calling callback for <Future at 0x4470048 state=finished returned Buffer>
Traceback (most recent call last):
  File "C:\python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\python37\lib\site-packages\opcua\client\ua_client.py", line 463, in _call_publish_callback
    self._uasocket.check_answer(data, "while waiting for publish response")
  File "C:\python37\lib\site-packages\opcua\client\ua_client.py", line 88, in check_answer
    hdr.ServiceResult.check()
  File "C:\python37\lib\site-packages\opcua\ua\uatypes.py", line 233, in check
    raise UaStatusCodeError(self.value)
opcua.ua.uaerrors._auto.BadSessionClosed: The session was closed by the client.(BadSessionClosed)`

The Code I am using looks like this:

`import sys
from threading import Thread
import logging
import time
from opcua import Client, ua
from opcua import Subscription
import xlrd
import os
from os.path import dirname

sys.path.insert(0, "..")

opc_connected = False

# Data change handler for measurement change
class SubHandler1(object):

    def datachange_notification(self, node, val, data):
        print("Data changed.", node, val)
        CallViews()

# Data change handler for server state change
class SubHandler2(object):

    def datachange_notification(self, node, val, data):
        print("OPC UA server state changed.")

# Thread for handling data change
class CallViews(Thread):

    def __init__(self):
        Thread.__init__(self)
        self.daemon = True
        self.running = True
        self.start()

    def stop(self):
        self.running = False

    def run(self):
        while self.running:
            try:
                read_Laser1_PartID()
                read_Laser1_MaterialID()
                read_Laser1_Positions()

                read_Laser1_Values()
                read_Laser2_Values()
                read_Laser3_Values()
                read_Laser4_Values()

                read_All_Quality()

                self.stop()
            except:
                print("Could not load changed data.")
        else:
            self.stop()

# Check if Connection to OPC UA server is possible
class ConnectionChecker(Thread):

    def __init__(self):
        Thread.__init__(self)
        self.daemon = True
        self.running = True
        self.start()

    def stop(self):
        disconnect()
        self.running = False

    def run(self):
        while self.running:
            if opc_connected:
                time.sleep(1)  # Checks every second if get_value is possible
                try:
                    print("Checking server connection.")
                    if not status.get_value() == 0:  # Connected to OPC UA server
                        print("Connection to OPC UA server failed. Please reconnect.")
                        self.stop()
                except:
                    print("Connection to OPC UA server failed.")
                    self.stop()
            else:
                self.stop()
        else:
            self.stop()

def loadSettings():
    # load OPC UA NodeIDs
    workingdir = os.path.dirname(os.path.realpath(__file__))

    global ServerState, values_Laser1, timeStamp_Laser1, positions_Laser1, quality_Laser1, partID_Laser1, \
        materialID_Laser1, values_Laser2, timeStamp_Laser2, positions_Laser2, quality_Laser2, partID_Laser2, \
        materialID_Laser2, values_Laser3, timeStamp_Laser3, positions_Laser3, quality_Laser3, partID_Laser3, \
        materialID_Laser3, values_Laser4, timeStamp_Laser4, positions_Laser4, quality_Laser4, partID_Laser4, \
        materialID_Laser4, exportOPCUA, measurementServerAddress

    try:
        book_opcua = xlrd.open_workbook(workingdir + '/Settings.xls')
        sheet_opua = book_opcua.sheet_by_index(0)

        measurementServerAddress = sheet_opua.cell_value(18, 0)
        ServerState = sheet_opua.cell_value(21, 0)

        values_Laser1 = sheet_opua.cell_value(23, 0)
        timeStamp_Laser1 = sheet_opua.cell_value(24, 0)
        positions_Laser1 = sheet_opua.cell_value(25, 0)
        quality_Laser1 = sheet_opua.cell_value(26, 0)
        partID_Laser1 = sheet_opua.cell_value(27, 0)
        materialID_Laser1 = sheet_opua.cell_value(28, 0)

        values_Laser2 = sheet_opua.cell_value(30, 0)
        timeStamp_Laser2 = sheet_opua.cell_value(31, 0)
        positions_Laser2 = sheet_opua.cell_value(32, 0)
        quality_Laser2 = sheet_opua.cell_value(33, 0)
        partID_Laser2 = sheet_opua.cell_value(34, 0)
        materialID_Laser2 = sheet_opua.cell_value(35, 0)

        values_Laser3 = sheet_opua.cell_value(37, 0)
        timeStamp_Laser3 = sheet_opua.cell_value(38, 0)
        positions_Laser3 = sheet_opua.cell_value(39, 0)
        quality_Laser3 = sheet_opua.cell_value(40, 0)
        partID_Laser3 = sheet_opua.cell_value(41, 0)
        materialID_Laser3 = sheet_opua.cell_value(42, 0)

        values_Laser4 = sheet_opua.cell_value(44, 0)
        timeStamp_Laser4 = sheet_opua.cell_value(45, 0)
        positions_Laser4 = sheet_opua.cell_value(46, 0)
        quality_Laser4 = sheet_opua.cell_value(47, 0)
        partID_Laser4 = sheet_opua.cell_value(48, 0)
        materialID_Laser4 = sheet_opua.cell_value(49, 0)

        print("Successfully loaded OPC UA settings.")

    except FileNotFoundError:
        print("Could not load OPC UA settings! Check settings file.")

# Connect to OPC UA server
def connect():
    global measurementServer, opc_connected
    logging.basicConfig(level=logging.WARN)

    #try:
    measurementServer = Client(measurementServerAddress)

    params = ua.CreateSubscriptionParameters()
    params.RequestedPublishingInterval = 500
    params.RequestedLifetimeCount = 3000
    params.RequestedMaxKeepAliveCount = 10000
    params.MaxNotificationsPerPublish = 10000
    params.PublishingEnabled = True
    params.Priority = 0

    measurementServer.connect()
    opc_connected = True

    trigger = measurementServer.get_node(partID_Laser1)

    # check for changes trigger changes
    handler1 = SubHandler1()
    sub1 = measurementServer.create_subscription(params, handler1)
    handle1 = sub1.subscribe_data_change(trigger)
    time.sleep(0.1)

    # check for server state changes to check connection
    handler2 = SubHandler2()
    sub2 = measurementServer.create_subscription(params, handler2)
    global status
    status = measurementServer.get_node(ServerState)
    handle2 = sub2.subscribe_data_change(status)
    time.sleep(0.1)
    ConnectionChecker()

    print("Connected to OPC UA server.")

    #except:
       # disconnect()
       # print("OPC UA connection error.")

# Disconnect from OPC UA server
def disconnect():
    try:
        measurementServer.disconnect()
        opc_connected = False
        print("Disconnected from OPA UA server.")
    except:
        opc_connected = False

# Read parameters of OPC UA server
def read_Laser1_PartID():
    try:
        partID = measurementServer.get_node(partID_Laser1)
        partID_value = partID.get_value()
        print("PartID: " + str(partID_value))
    except:
        disconnect()
        print("OPC UA error while trying to read partID.")

def read_Laser1_MaterialID():
    try:
        materialID = measurementServer.get_node(materialID_Laser1)
        materialID_value = materialID.get_value()
        print("MaterialID: " + str(materialID_value))
    except:
        disconnect()
        print("OPC UA error while trying to read materialID.")

def read_Laser1_Positions():
    try:
        positions = measurementServer.get_node(positions_Laser1)
        positions_value = positions.get_value()
        print("Laser1 Positions: " + str(positions_value))
    except:
        disconnect()
        print("OPC UA error while trying to read positions.")

def read_Laser1_Values():
    try:
        values1 = measurementServer.get_node(values_Laser1)
        values1_value = values1.get_value()
        print("Laser1 Values: " + str(values1_value))
    except:
        disconnect()
        print("OPC UA error while trying to read Laser1 values.")

def read_Laser2_Values():
    try:
        values2 = measurementServer.get_node(values_Laser2)
        values2_value = values2.get_value()
        print("Laser2 Values: " + str(values2_value))
    except:
        disconnect()
        print("OPC UA error while trying to read Laser2 values.")

def read_Laser3_Values():
    try:
        values3 = measurementServer.get_node(values_Laser3)
        values3_value = values3.get_value()
        print("Laser3 Values: " + str(values3_value))
    except:
        disconnect()
        print("OPC UA error while trying to read Laser3 values.")

def read_Laser4_Values():
    try:
        values4 = measurementServer.get_node(values_Laser4)
        values4_value = values4.get_value()
        print("Laser4 Values: " + str(values4_value))
    except:
        disconnect()
        print("OPC UA error while trying to read Laser4 values.")

def read_All_Quality():
    try:
        # Laser1
        quality1 = measurementServer.get_node(quality_Laser1)
        quality_values1 = quality1.get_value()
        # Laser2
        quality2 = measurementServer.get_node(quality_Laser2)
        quality_values2 = quality2.get_value()
        # Laser3
        quality3 = measurementServer.get_node(quality_Laser3)
        quality_values3 = quality3.get_value()
        # Laser4
        quality4 = measurementServer.get_node(quality_Laser4)
        quality_values4 = quality4.get_value()

        quality_values_all = quality_values1 + quality_values2 + quality_values3 + quality_values4
        print("Quality: " + str(quality_values_all))
    except:
        disconnect()
        print("OPC UA error while trying to read quality.")

if __name__ == "__main__":
    loadSettings()
    # Connect to OPC UA server
    connect()
    read_Laser1_PartID()
    read_Laser1_MaterialID()
    read_Laser1_Positions()

    read_Laser1_Values()
    read_Laser2_Values()
    read_Laser3_Values()
    read_Laser4_Values()

    read_All_Quality()
`
I have some guesses what the problem could be:

1. Creating a new thread called by the subscription is the problem.
2. The subscription event gets called 2x times after connecting to the server.
3. Parameter settings e.g.     params.RequestedMaxKeepAliveCount = 10000 or  params.MaxNotificationsPerPublish = 10000

Thank you very much for your support!

**Comment by jkbngl** [comment]
HI @OPCle I am facing the same issue, found anything that has caused the issue?

**Comment by ColinISW** [comment]
Hi, @jkbngl Not really..., but I guess that it was caused by to heavy reading. So, what I did (and now it's working):

1. Try it with only reading one value - does the error still occur?

2. I am currently using these parameters for my client: 

```
params = ua.CreateSubscriptionParameters()
params.RequestedPublishingInterval = 500
params.RequestedLifetimeCount = 3000
params.RequestedMaxKeepAliveCount = 10000
params.MaxNotificationsPerPublish = 2147483647
params.PublishingEnabled = True
params.Priority = 0
```

3. Added some time.sleep(0.1) after reading a value so the server can process everything.

I hope it helps you.

**Comment by zerox1212** [comment]
Your issue is not very well formatted and is hard to read. I don't think many people will help you with a post like this.

Anyways you are doing some things I definitely don't understand. Why do you need a thread to read values? Why does reading the values have to get the node every time the function is called? Why not just create a subscription for all your laser/quality values?

**Comment by OPCle** [comment]
Yes, you're right..sorry - tried to fix the code highlighting.

1. I am creating threads because the [python example](https://github.com/FreeOpcUa/python-opcua/blob/master/examples/client-example.py) says for SubHandlers:

>  Subscription Handler. To receive events from server for a subscription
    data_change and event methods are called directly from receiving thread.
    Do not do expensive, slow or network operation there. Create another 
    thread if you need to do such a thing
   
Without these threads it is not working.

2. The values are not very often read (~every 15 minutes during production) and to make a subscription for each value seems to be a little much. Because of that I am subscribing only to one node and read the others after this one changed.

**Comment by zerox1212** [comment]
I see. If this code works when using your own network/server then isn't it more likely a network or infrastructure issue?
