### ISSUE TITLE
Error when deleting nodes with active data subscripts

### ISSUE THREAD

**Issue by simmarn** [FreeOpcUa/python-opcua#851]
Hi,

When I try to delete a node with active data subscriptions I get the following error:
--

> Traceback (most recent call last):
>   File "OPC-UA_Server.py", line 618, in main
>     update_nodes(message, objects, idx, server)
>   File "OPC-UA_Server.py", line 465, in update_nodes
>     remove_mission(data, objects, idx)
>   File "OPC-UA_Server.py", line 400, in remove_mission
>     recursive_node_removal(mission, removed_nodes)
>   File "OPC-UA_Server.py", line 66, in recursive_node_removal
>     recursive_node_removal(sub_node, output_list)
>   File "OPC-UA_Server.py", line 67, in recursive_node_removal
>     node.delete()
>   File "site-packages\opcua\common\node.py", line 578, in delete
>   File "site-packages\opcua\common\manage_nodes.py", line 390, in delete_nodes
>   File "site-packages\opcua\server\internal_server.py", line 360, in delete_nodes
>   File "site-packages\opcua\server\address_space.py", line 308, in delete_nodes
>   File "site-packages\opcua\server\address_space.py", line 325, in _delete_node
>   File "site-packages\opcua\server\address_space.py", line 333, in _delete_node_callbacks
> RuntimeError: dictionary changed size during iteration

--

The following seems to fix it:
```
diff --git a/opcua/server/address_space.py b/opcua/server/address_space.py
index 20e5dcd..588263b 100644
--- a/opcua/server/address_space.py
+++ b/opcua/server/address_space.py
@@ -330,7 +330,10 @@ class NodeManagementService(object):

     def _delete_node_callbacks(self, nodedata):
         if ua.AttributeIds.Value in nodedata.attributes:
+            items = []
             for handle, callback in list(nodedata.attributes[ua.AttributeIds.Value].datachange_callbacks.items()):
+                items.append((handle, callback))
+            for handle, callback in items:
                 try:
                     callback(handle, None, ua.StatusCode(ua.StatusCodes.BadNodeIdUnknown))
                     self._aspace.delete_datachange_callback(handle)

```

I can create a PR if you like.

BR,
-Martin

**Comment by simmarn** [comment]
Never mind, it was already fixed.
