### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by seemas7** [FreeOpcUa/python-opcua#904]
I am new to python and OPCUA 
I installed opcua using pip install opcua

i am importing Client as 
from opcua import Client

But I get the below error :
Traceback (most recent call last):
  File "e:/Projects/OPCUA/opcua.py", line 1, in <module>
    from opcua import Client
  File "e:\Projects\OPCUA\opcua.py", line 1, in <module>
    from opcua import Client
ImportError: cannot import name 'Client'

Please help

**Comment by tdesroches** [comment]
try pip install freeopcua
