### ISSUE TITLE
Not able to continuous run the opc client

### ISSUE THREAD

**Issue by juhiajmera13** [FreeOpcUa/python-opcua#944]
Hi

I am trying to run the client code for a long time, but it is shutting down every now and then. Can someone help?

**Comment by oroulet** [comment]
you need to write down your setup, what server, what authentication, encryption
and of course send the stack trace here

**Comment by juhiajmera13** [comment]
This is what I am trying to do:

var=client.get_node("ns=4;i=4000")
client=Client(url)
client.connect()
print("Connected")
try:
    while True:
          print(var.get_value())
except ConnectionError as e:    # This is the correct syntax
   print(e)
   r = "No response"


I want to run this for a few days to get data from the machine. But, the code is getting shut down every now and then randomly. The errors what I am getting are:

File "<ipython-input-3-c604fa2d7fd3>", line 1, in <module>
    runfile('C:/Users/E0559351/Documents/AMMachine/client_v2.python.py', wdir='C:/Users/E0559351/Documents/AMMachine')

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/E0559351/Documents/AMMachine/client_v2.python.py", line 19, in <module>
    client.connect()

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\opcua\client\client.py", line 257, in connect
    self.send_hello()

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\opcua\client\client.py", line 289, in send_hello
    ack = self.uaclient.send_hello(self.server_url.geturl(), self.max_messagesize, self.max_chunkcount)

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\opcua\client\ua_client.py", line 251, in send_hello
    return self._uasocket.send_hello(url, max_messagesize, max_chunkcount)

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\site-packages\opcua\client\ua_client.py", line 177, in send_hello
    ack = future.result(self.timeout)

  File "C:\Users\E0559351\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py", line 437, in result
    raise TimeoutError()

TimeoutError

**Comment by juhiajmera13** [comment]
I want to run the client application continuously but the client disconnects and doesn't automatically connect.

**Comment by jehanjoshi007** [comment]
Is this issue resolved ?

**Comment by oroulet** [comment]
This big report does not point to an issue. It is too vague. You can get timeout for 1000s reasons

**Comment by fcaspani01** [comment]
Hi @oroulet,
I have the same issue of @jehanjoshi007.
Can I increase timeout value for get_value() function?

**Comment by oroulet** [comment]
No. It does not help anything. The timeout just says the communication is down. Increasing the timeout just warns you later. There is probably another stack trace before telling you what the real error is. Maybe some buffer or socket error or server error

**Comment by fcaspani01** [comment]
Ok thanks, what do you suggest in this case?

**Comment by oroulet** [comment]
Wait for next crash and find the real stop reason. Then open a bug report

**Comment by oroulet** [comment]
Must be another error BEFORE the timeout error

**Comment by oroulet** [comment]
Yes. You can also serve the Wireshark trace here. This is the best debug data we can get

**Comment by jehanjoshi007** [comment]
@oroulet  thanks the next time I face the same issue I will share the wireshark trace here.

**Comment by jehanjoshi007** [comment]
@oroulet I was able to reproduce the issue this was the error I got the code apparently runs for a few weeks and then raises a timeout error 

`import pyodbc
import psycopg2 
import pandas as pd 
import datetime as dt
import collections 
import opcua
from opcua import *
import socket
import sys 
import urllib.parse
import time, uuid
import urllib.request
import hmac, hashlib
from base64 import b64encode
from json import loads
import concurrent.futures
import gc
import numpy as np
clientc = Client("")
clientc.connect()
def database_connection():

    try:
    
        conn = psycopg2.connect("")
        cur = conn.cursor()
    
        return cur,conn

    except:

        dc = "error"

    

def plant_temp():
    try:
        ts = str(int(time.time()))
        with urllib.request.urlopen() as response:
            html = response.read()
            data= html.decode('utf-8')

   
        l = []
        l.append(data)
#     seq1 ='bTemperature'
#     seq2 ='\nc'
        l = [item.replace(' ','') for item in l]
        l = [item.split('\n') for item in l]

    #print(l)
        for ele in l:
        #print(ele)
    
            Temperature = ele[1][12:16]
            Humidity = ele[2][9:13]
            Dewpoint = ele[3][9:13]
            response.close()
    
        return Temperature,Humidity,Dewpoint

    except:
        print("Error")
    

def get_temp_hum():

    try:
        
        url = 'https://weather-ydn-yql.media.yahoo.com/forecastrss'
        method = 'GET'
        app_id = 'ub9BBk6e'
        consumer_key = ''
        consumer_secret = ''
        concat = '&'
        query = {'location': 'athens,ga', 'format': 'json'}
        oauth = {
            'oauth_consumer_key': consumer_key,
            'oauth_nonce': uuid.uuid4().hex,
            'oauth_signature_method': 'HMAC-SHA1',
            'oauth_timestamp': str(int(time.time())),
            'oauth_version': '1.0'}

        merged_params = query.copy()

        merged_params.update(oauth)
        #print("merged params{}".format(merged_params))
        sorted_params = [k + '=' + urllib.parse.quote(merged_params[k], safe='') for k in sorted(merged_params.keys())]
        #print("sorted params are{}".format(sorted_params))
        signature_base_str = method + concat + urllib.parse.quote(url, safe='') + concat + urllib.parse.quote(concat.join(sorted_params), safe='')

        #print("signature base string {}".format(signature_base_str))

        #Generate signature

        composite_key = urllib.parse.quote(consumer_secret, safe='') + concat
        #print(composite_key)
        oauth_signature = b64encode(hmac.new(composite_key.encode('utf-8'), signature_base_str.encode('utf-8'), hashlib.sha1).digest())
        #Prepare Authorization header

        oauth['oauth_signature'] = oauth_signature.decode('utf-8')
        auth_header = 'OAuth ' + ', '.join(['{}="{}"'.format(k,v) for k,v in oauth.items()])
        #Send request

        url = url + '?' + urllib.parse.urlencode(query)
        request = urllib.request.Request(url)
        request.headers['Authorization'] = auth_header
        request.headers['X-Yahoo-App-Id']= app_id
        response = urllib.request.urlopen(request).read()


    # for weather in response:
    #     print(weather)
        response = loads(response)

#print(response)
    
        humidity = 0
        temperature = 0
    
        for key,value in response.items():
            if key == 'current_observation':
                current_weather = value
            #print(current_weather)
                humidity = current_weather['atmosphere']['humidity']
                temperature = current_weather['condition']['temperature']
        

        return humidity,temperature

    except:

        print("error")
        
          
            
            
            
           
           
        
    #print(key, "--->" , value)
#print(response)
    
    
def line3_insert(cur,conn):
    
    try:
        clientc = Client("")
        clientc.connect()
    
        num_rows = 0
    
    
        line3id      =  clientc.get_node("ns=3;s=Line3ID")
        line3speed   =  clientc.get_node("ns=3;s=Line3ScraySpeed")
        line3product =  clientc.get_node("ns=3;s=line3Product")
        line3status  =  clientc.get_node("ns=3;s=Line3Status")
        line3maintcall= clientc.get_node("ns=3;s=Line3MaintCall")
        line3spare1  =  clientc.get_node("ns=3;s=Line3Spare1")
        line3spare2  =  clientc.get_node("ns=3;s=Line3Spare2")
        line3spare3  =  clientc.get_node("ns=3;s=Line3Spare3")
        line3spare4  =  clientc.get_node("ns=3;s=Line3Spare4")
    
    
        line3idval   =  line3id.get_value()
        line3prodval   =  line3product.get_value()
        line3statval = line3status.get_value()
        line3maintval = line3maintcall.get_value()
        line3spa1val = line3spare1.get_value()
        line3spa2val = line3spare2.get_value()
        line3spa3val = line3spare3.get_value()
        line3spa4val = line3spare4.get_value()
        line3spval = line3speed.get_value()
    
        humidity,temperature = get_temp_hum()
        PlantTemperature,PlantHumidity,PlantDewpoint = plant_temp()
    
        unix = int(time.time()) #Epoch time in seconds 
    
        insert_line3stg = ("""insert into line3_stg (line3_id,line3_maintcall,line3_product,
                      line3_scrayspeed,line3_spare1,line3_spare2,line3_spare3,line3_spare4,
                      line3_status,line3_unix,temp,humidity,plant_temp,plant_hum,plant_dewpoint)
                      values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""")
    
    
        cur.execute(insert_line3stg,[line3idval,line3maintval,line3prodval,line3spval,line3spa1val,\
               line3spa2val,line3spa3val,line3spa4val,line3statval,unix,temperature,humidity,\
                                     PlantTemperature,PlantHumidity,PlantDewpoint])
    
        conn.commit()
    
    #     data = [line3idval,line3prodval,line3statval,line3maintval,line3spa1val,\
    #            line3spa2val,line3spa3val,line3spa4val,line3spval] 
    
    #     header = [lineid,line3product]
    
    #     for element in data:
    
    
#        print(humidity,temperature)
#        print("the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              .format('line3idval',line3idval,'line3prodval',line3prodval,'line3statval',\
#                      line3statval,'line3maintval',line3maintval,'line3spa1val',line3spa1val,\
#                      'line3spa2val',line3spa2val,'line3spa3val',line3spa3val,'line3spa4val',\
#                      line3spa4val,'line3spval',line3spval))
#    
#    
#    
#        num_rows += 1
#    
#        print("the number of rows inserted {}".format(num_rows))
#    
        clientc.disconnect()
#        
    except:
        a="ERROR"
        
def line4_insert(cur,conn):
    
    try:
        clientc = Client("")
        clientc.connect()
    
        num_rows = 0
    
    
        line4id      =  clientc.get_node("ns=3;s=Line4ID")
        line4speed   =  clientc.get_node("ns=3;s=Line4ScraySpeed")
        line4product =  clientc.get_node("ns=3;s=line4Product")
        line4status  =  clientc.get_node("ns=3;s=Line4Status")
        line4maintcall= clientc.get_node("ns=3;s=Line4MaintCall")
        line4spare1  =  clientc.get_node("ns=3;s=Line4Spare1")
        line4spare2  =  clientc.get_node("ns=3;s=Line4Spare2")
        line4spare3  =  clientc.get_node("ns=3;s=Line4Spare3")
        line4spare4  =  clientc.get_node("ns=3;s=Line4Spare4")
    
    
        line4idval   =  line4id.get_value()
        line4prodval   =  line4product.get_value()
        line4statval = line4status.get_value()
        line4maintval = line4maintcall.get_value()
        line4spa1val = line4spare1.get_value()
        line4spa2val = line4spare2.get_value()
        line4spa3val = line4spare3.get_value()
        line4spa4val = line4spare4.get_value()
        line4spval = line4speed.get_value()
    
        humidity,temperature = get_temp_hum()
        PlantTemperature,PlantHumidity,PlantDewpoint = plant_temp()
    
        unix = int(time.time()) #Epoch time in seconds 
    
        insert_line4stg = ("""insert into line4_stg (line4_id,line4_maintcall,line4_product,
                  line4_scrayspeed,line4_spare1,line4_spare2,line4_spare3,line4_spare4,
                  line4_status,line4_unix,temp,humidity,plant_temp,plant_hum,plant_dewpoint)
                  
                  values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""")
    
    
    
        cur.execute(insert_line4stg,[line4idval,line4maintval,line4prodval,line4spval,line4spa1val,\
               line4spa2val,line4spa3val,line4spa4val,line4statval,unix,temperature,humidity,\
                                    PlantTemperature,PlantHumidity,PlantDewpoint])
    
        conn.commit()
    
    #     data = [line3idval,line3prodval,line3statval,line3maintval,line3spa1val,\
    #            line3spa2val,line3spa3val,line3spa4val,line3spval] 
    
    #     header = [lineid,line3product]
    
    #     for element in data:
    
    
#        print(humidity,temperature)
#        print("the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              .format('line4idval',line4idval,'line4prodval',line4prodval,'line4statval',\
#                      line4statval,'line4maintval',line4maintval,'line4spa1val',line4spa1val,\
#                      'line4spa2val',line4spa2val,'line4spa3val',line4spa3val,'line4spa4val',\
#                      line4spa4val,'line4spval',line4spval))
#    
#    
#    
#        num_rows += 1
#    
#        print("the number of rows inserted {}".format(num_rows))
    
        clientc.disconnect()
        
    except:
        
        a="ERROR"

def line5_insert(cur,conn):
    
    try:
        clientc = Client("")
        clientc.connect()
    
        num_rows = 0
    
    
        line5id      =  clientc.get_node("ns=3;s=Line5ID")
        line5speed   =  clientc.get_node("ns=3;s=Line5ScraySpeed")
        line5product =  clientc.get_node("ns=3;s=line5Product")
        line5status  =  clientc.get_node("ns=3;s=Line5Status")
        line5maintcall= clientc.get_node("ns=3;s=Line5MaintCall")
        line5spare1  =  clientc.get_node("ns=3;s=Line5Spare1")
        line5spare2  =  clientc.get_node("ns=3;s=Line5Spare2")
        line5spare3  =  clientc.get_node("ns=3;s=Line5Spare3")
        line5spare4  =  clientc.get_node("ns=3;s=Line5Spare4")
    
    
        line5idval   =  line5id.get_value()
        line5prodval   =  line5product.get_value()
        line5statval = line5status.get_value()
        line5maintval = line5maintcall.get_value()
        line5spa1val = line5spare1.get_value()
        line5spa2val = line5spare2.get_value()
        line5spa3val = line5spare3.get_value()
        line5spa4val = line5spare4.get_value()
        line5spval = line5speed.get_value()
    
        humidity,temperature = get_temp_hum()
        PlantTemperature,PlantHumidity,PlantDewpoint = plant_temp()
    
        unix = int(time.time()) #Epoch time in seconds 
    
        insert_line5stg = ("""insert into line5_stg (line5_id,line5_maintcall,line5_product,
                  line5_scrayspeed,line5_spare1,line5_spare2,line5_spare3,line5_spare4,
                  line5_status,line5_unix,temp,humidity,plant_temp,plant_hum,plant_dewpoint)
                  
                  values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""")
    
    
        cur.execute(insert_line5stg,[line5idval,line5maintval,line5prodval,line5spval,line5spa1val,\
               line5spa2val,line5spa3val,line5spa4val,line5statval,unix,temperature,humidity,\
                                    PlantTemperature,PlantHumidity,PlantDewpoint])
    
        conn.commit()
    
    #     data = [line3idval,line3prodval,line3statval,line3maintval,line3spa1val,\
    #            line3spa2val,line3spa3val,line3spa4val,line3spval] 
    
    #     header = [lineid,line3product]
    
    #     for element in data:
    
    
#        print(humidity,temperature)
#        print("the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              .format('line5idval',line5idval,'line5prodval',line5prodval,'line5statval',\
#                      line5statval,'line5maintval',line5maintval,'line5spa1val',line5spa1val,\
#                      'line5spa2val',line5spa2val,'line5spa3val',line5spa3val,'line5spa4val',\
#                      line5spa4val,'line5spval',line5spval))
#    
#    
#    
#        num_rows += 1
#    
#        print("the number of rows inserted {}".format(num_rows))
    
        clientc.disconnect()
        
    except:
        
        a="ERROR"

def line6_insert(cur,conn):
    
    try:
        clientc = Client("")
        clientc.connect()
    
        num_rows = 0
    
    
        line6id      =  clientc.get_node("ns=3;s=Line6ID")
        line6speed   =  clientc.get_node("ns=3;s=Line6ScraySpeed")
        line6product =  clientc.get_node("ns=3;s=line6Product")
        line6status  =  clientc.get_node("ns=3;s=Line6Status")
        line6maintcall= clientc.get_node("ns=3;s=Line6MaintCall")
        line6spare1  =  clientc.get_node("ns=3;s=Line6Spare1")
        line6spare2  =  clientc.get_node("ns=3;s=Line6Spare2")
        line6spare3  =  clientc.get_node("ns=3;s=Line6Spare3")
        line6spare4  =  clientc.get_node("ns=3;s=Line6Spare4")
    
    
        line6idval   =  line6id.get_value()
        line6prodval   =  line6product.get_value()
        line6statval = line6status.get_value()
        line6maintval = line6maintcall.get_value()
        line6spa1val = line6spare1.get_value()
        line6spa2val = line6spare2.get_value()
        line6spa3val = line6spare3.get_value()
        line6spa4val = line6spare4.get_value()
        line6spval = line6speed.get_value()
    
        humidity,temperature = get_temp_hum()
        PlantTemperature,PlantHumidity,PlantDewpoint = plant_temp()
    
        unix = int(time.time()) #Epoch time in seconds 
    
        insert_line6stg = ("""insert into line6_stg (line6_id,line6_maintcall,line6_product,
                  line6_scrayspeed,line6_spare1,line6_spare2,line6_spare3,line6_spare4,
                  line6_status,line6_unix,temp,humidity,plant_temp,plant_hum,plant_dewpoint)
                  
                  values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""")
    
    
        cur.execute(insert_line6stg,[line6idval,line6maintval,line6prodval,line6spval,line6spa1val,\
               line6spa2val,line6spa3val,line6spa4val,line6statval,unix,temperature,humidity,\
                                    PlantTemperature,PlantHumidity,PlantDewpoint])
    
        conn.commit()
    
    #     data = [line3idval,line3prodval,line3statval,line3maintval,line3spa1val,\
    #            line3spa2val,line3spa3val,line3spa4val,line3spval] 
    
    #     header = [lineid,line3product]
    
    #     for element in data:
    
    
#        print(humidity,temperature)
#        print("the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              .format('line6idval',line6idval,'line6prodval',line6prodval,'line6statval',\
#                      line6statval,'line6maintval',line6maintval,'line6spa1val',line6spa1val,\
#                      'line6spa2val',line6spa2val,'line6spa3val',line6spa3val,'line6spa4val',\
#                      line6spa4val,'line6spval',line6spval))
#    
#    
#    
#        num_rows += 1
#    
#        print("the number of rows inserted {}".format(num_rows))
    
        clientc.disconnect()
        
    except:
        
        a="ERROR"
        
def line7_insert(cur,conn):
    
    try:
        clientc = Client("")
        clientc.connect()
    
        num_rows = 0
    
    
        line7id      =  clientc.get_node("ns=3;s=Line7ID")
        line7speed   =  clientc.get_node("ns=3;s=Line7ScraySpeed")
        line7product =  clientc.get_node("ns=3;s=line7Product")
        line7status  =  clientc.get_node("ns=3;s=Line7Status")
        line7maintcall= clientc.get_node("ns=3;s=Line7MaintCall")
        line7spare1  =  clientc.get_node("ns=3;s=Line7Spare1")
        line7spare2  =  clientc.get_node("ns=3;s=Line7Spare2")
        line7spare3  =  clientc.get_node("ns=3;s=Line7Spare3")
        line7spare4  =  clientc.get_node("ns=3;s=Line7Spare4")
    
    
        line7idval   =  line7id.get_value()
        line7prodval   =  line7product.get_value()
        line7statval = line7status.get_value()
        line7maintval = line7maintcall.get_value()
        line7spa1val = line7spare1.get_value()
        line7spa2val = line7spare2.get_value()
        line7spa3val = line7spare3.get_value()
        line7spa4val = line7spare4.get_value()
        line7spval = line7speed.get_value()
    
        humidity,temperature = get_temp_hum()
        PlantTemperature,PlantHumidity,PlantDewpoint = plant_temp()
    
        unix = int(time.time()) #Epoch time in seconds 
    
        insert_line7stg = ("""insert into line7_stg (line7_id,line7_maintcall,line7_product,
                  line7_scrayspeed,line7_spare1,line7_spare2,line7_spare3,line7_spare4,
                  line7_status,line7_unix,temp,humidity,plant_temp,plant_hum,plant_dewpoint)
                  
                  values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""")
    
    
        cur.execute(insert_line7stg,[line7idval,line7maintval,line7prodval,line7spval,line7spa1val,\
               line7spa2val,line7spa3val,line7spa4val,line7statval,unix,temperature,humidity,\
                                    PlantTemperature,PlantHumidity,PlantDewpoint])
    
        conn.commit()
    
    #     data = [line3idval,line3prodval,line3statval,line3maintval,line3spa1val,\
    #            line3spa2val,line3spa3val,line3spa4val,line3spval] 
    
    #     header = [lineid,line3product]
    
    #     for element in data:
    
    
#        print(humidity,temperature)
#        print("the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              "the {} is {}\n"\
#              .format('line7idval',line7idval,'line7prodval',line7prodval,'line7statval',\
#                      line7statval,'line7maintval',line7maintval,'line7spa1val',line7spa1val,\
#                      'line7spa2val',line7spa2val,'line7spa3val',line7spa3val,'line7spa4val',\
#                      line7spa4val,'line7spval',line7spval))
#    
#    
#    
#        num_rows += 1
#    
#        print("the number of rows inserted {}".format(num_rows))
    
        clientc.disconnect()
        
    except:
        
        a="ERROR"

def main():
#    t1 = time.perf_counter()
    try:
        
        mode_auto()
        cur,conn = database_connection()
        line3_insert(cur,conn)
        line4_insert(cur,conn)
        line5_insert(cur,conn)
        line6_insert(cur,conn)
        line7_insert(cur,conn)
        conn.close()
        cur.close()

    except:
        m = "error"
    
#    t2 = time.perf_counter()
#    print("time taken is {} seconds".format(round(t2-t1,2)))

if __name__ == "__main__":
    
    while True:
        try:
            main()
            #gc.collect()
            time.sleep(55)
        except:
            m = "error"`

File "C:\Users\jehan.SKAPS\Desktop\PythonOPC\OPC_LiveV10.py", line 39, in <module>
    clientc.connect()

  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\client.py", line 257, in connect
    self.send_hello()

  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\client.py", line 289, in send_hello
    ack = self.uaclient.send_hello(self.server_url.geturl(), self.max_messagesize, self.max_chunkcount)

  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\ua_client.py", line 251, in send_hello
    return self._uasocket.send_hello(url, max_messagesize, max_chunkcount)

  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\ua_client.py", line 177, in send_hello
    ack = future.result(self.timeout)

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 434, in result
    raise TimeoutError()

TimeoutError

**Comment by maintainenceskaps** [comment]
@oroulet  when we run the script the fetch data continuously we get the following error as well and we cannot connect to the opc ua server 

>>> from opcua import *
>>> clientc = Client("opc.tcp://10.1.4.208:4870")
>>> clientc.connect()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\client.py", line 274, in connect
    self.send_hello()
  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\client.py", line 306, in send_hello
    ack = self.uaclient.send_hello(self.server_url.geturl(), self.max_messagesize, self.max_chunkcount)
  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\ua_client.py", line 262, in send_hello
    return self._uasocket.send_hello(url, max_messagesize, max_chunkcount)
  File "C:\ProgramData\Anaconda3\lib\site-packages\opcua\client\ua_client.py", line 190, in send_hello
    ack = future.result(self.timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 430, in result
    raise CancelledError()
concurrent.futures._base.CancelledError

Interesting thing is the dashboard is built in node red and node red has no issues at all in maintaining a continuous connection with the opc ua server so this should not be a server issue

**Comment by oroulet** [comment]
From the stack above you are not running for a few weeks but trying to connect and failing. If you are not running continuously then just add a try and except. And retry any errors.
But I have no ideas why the server refuses the connection. This is before any session creation it sounds more like a network error or similar

**Comment by maintainenceskaps** [comment]
@oroulet It was running continuously and then the timeout error happens I have try and except but it keeps trying and I keep seeing a timeout error this is only resolved when I restart the opc ua server which is in a Siemens HMI screen. The python exe file I have created runs for a few days and then timeout error occurs after which until I restart the server it will never connect back 



[TimeOutSelected1.zip](https://github.com/FreeOpcUa/python-opcua/files/4717345/TimeOutSelected1.zip)

I ran this stack to just show the stack trace I have attached the wireshark trace as well if that would be helpful to figure out what happened.
